name: Talktune Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_CHAT_API_SK: ${{ secrets.CHAT_API_SK }}
      REACT_APP_FINE_TUNED_MODEL_API_SK: ${{ secrets.FINE_TUNED_MODEL_API_SK }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          REACT_APP_CHAT_API_SK: ${{ secrets.CHAT_API_SK }}
          REACT_APP_FINE_TUNED_MODEL_API_SK: ${{ secrets.FINE_TUNED_MODEL_API_SK }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/talktune:latest
